official_skill_regex = {
    "Java|programming language": ["(java|jee|j2ee)"],
    "Python|programming language": ["python"],
    "CSharp|programming language": ["(c#|csharp)", "c\s+sharp"],
    "Objective-C|programming language": ["(objectivec|objective.c|objective-c)", "objective\s+c"],
    "Golang|programming language": ["(go|golang)", "go\s+(language|programming|\(programming|\(language)"],
    "Kotlin|programming language": ["kotlin"],
    "Rust|programming language": ["rust"],
    "VB.Net|programming language": ["(vb\.net|vbnet)", "(vb|visual)\s+(\.net|dotnet|net)", "visual\s+basic\s+(\.net|dotnet|net)"],
    "ASP.Net|programming language": ["(asp\.net|aspnet)", "asp\s+(\.net|dotnet|net)"],
    "Bash|programming language": ["bash"],
    "Visual Basic 6|programming language": ["(vb6|vb\.6|vb\s+6)", "visual\s+basic\s+6"],
    "C|programming language": ["\w+\sc\s\w+", "\w+\sc,", ",\sc,"],
    "C++|programming language": ["(c\+\+|c\s+\+\+|c\s+\+\s+\+)"],
    "CSS|programming language": ["(css|css3)"],
    "GraphQL|programming language": ["graphql"],
    "HTML|programming language": ["(html|html5)"],
    "JavaScript|programming language": ["(javascript|java/s+script)"],
    "Language Integrated Query (LINQ)|programming language": ["linq", "language\s+integrated\s+query"],
    "MatLab|programming language": ["matlab"],
    "NodeJS|programming language": ["nodejs", "node\.js", "node\s+(js|\.js)"],
    "Perl|programming language": ["perl"],
    "PHP|programming language": ["php"],
    "Ruby|programming language": ["ruby"],
    "Scala|programming language": ["scala"],
    "Shell|programming language": ["shell"],
    "PowerShell|programming language": ["powershell", "power\s+shell"],
    "Swift|programming language": ["swift"],
    "R|programming language": ["\w+\sr\s\w+", "\w+\sr,", "r,"],
    "TypeScript|programming language": ["typescript", "type\s+script"],
    "SQL|programming language": ["(sql|tsql|psql)"],
    "ADO.Net|framework": ["(ado\.net|adonet)", "ado\s+(\.net|dotnet|net)"],
    "Asynchronous JavaScript and XML (AJAX)|framework": ["ajax", "asynchronous\s+javascript\s+and\s+xml"],
    "Angular|framework": ["(angular|angular2)"],
    "Angular.JS|framework": ["(angular\.js|angularjs)"],
    "Apache Spark|framework": ["spark"],
    "Bootstrap|framework": ["bootstrap", "boot\s+strap"],
    "Django|framework": ["django"],
    "ElasticSearch|framework": ["elastic\s+search", "elasticsearch"],
    "Entity Framework|framework": ["entity\s+framework"],
    "Express.JS|framework": ["(express|express\.js|expressjs)"],
    "Flask|framework": ["flask"],
    "Hibernate|framework": ["hibernate"],
    "JavaServer Pages (JSP)|framework": ["jsp", "java\s+server\s+pages", "javaserver\s+pages"],
    "Java Database Connectivity (JDBC)|framework": ["jdbc", "java\s+database\s+connectivity"],
    "jQuery|framework": ["jquery"],
    "JUnit|framework": ["junit"],
    "OpenGL|framework": ["opengl", "open\s+gl"],
    "React.JS|framework": ["(react\.js|reactjs|react)"],
    "React Native|framework": ["react\s+native"],
    "Redux|framework": ["redux"],
    "Selenium|framework": ["selenium"],
    "Java Servlets|framework": ["servlet|servlets"],
    "Spring Boot|framework": ["spring\s+boot"],
    "Spring Framework|framework": ["spring"],
    "Spring MVC|framework": ["spring\s+mvc"],
    "SQL Server Reporting Services (SSRS)|framework": ["ssrs", "sql\s+server\s+reporting\s+services"],
    "Apache Struts|framework": ["struts"],
    "TensorFlow|framework": ["tensorflow", "tensor\s+flow"],
    "Unity|framework": ["unity", "unity3d"],
    "Vue.JS|framework": ["(vue\.js|vuejs)", "vue\s+(js|\.js)"],
    "Windows Communication Foundation (WCF)|framework": ["wcf", "windows\s+communication\s+foundation"],
    "WordPress|framework": ["wordpress", "word\s+press"],
    "Windows Presentation Foundation (WPF)|framework": ["wpf", "windows\s+presentation\s+foundation"],
    "SQL Server Integration Services (SSIS)|framework": ["ssis", "sql\s+server\s+integration\s+services"],
    "DB2|database": ["db2", "db\s+2"],
    "Microsoft SQL Server|database": ["sql\s+server"],
    "MongoDB|database": ["mongo", "mongodb"],
    "MySQL|database": ["mysql"],
    "Oracle Database|database": ["oracledb", "oracle/s+(database|db|sql)"],
    "PostgreSQL|database": ["postgres", "postgresql"],
    "Redis|database": ["redis"],
    "SQLite|database": ["sqlite"],
    "MariaDB|database": ["mariadb", "maria\s+(db|database)"],
    "IBM Informix|database": ["informix"],
    "SAP HANA|database": ["sap/s+hana"],
    "Apache Derby|database": ["apache\s+derby"],
    "Firebird|database": ["firebird"],
    "Apache Cassandra|database": ["cassandra"],
    "CockroachDB|database": ["cockroachdb", "cockroach\s+(db|database)"],
    "Microsoft Access|database": ["microsoft\s+access", "Access"],
    "Vertica|database": ["vertica"],
    "Amazon Aurora|database": ["amazon\s+aurora"],
    "Apache CouchDB|database": ["couchdb", "couch\s+(db|database)"],
    "Apache HBase|database": ["hbase"],
    "Couchbase|database": ["couchbase"],
    "ArangoDB|database": ["arangodb", "arango\s+(db|database)"],
    "Aerospike|database": ["aerospike"],
    "RiaK|database": ["riak"],
    "MarkLogic|database": ["marklogic"],
    "Extensible Markup Language (XML)|software engineering": ["xml"],
    "Google Cloud Datastore|database": ["google\s+cloud\s+datastore"],
    "FaunaDB|database": ["faunadb", "fauna\s+(db|database)"],
    "Apache Ignite|database": ["ignite"],
    "GridGain|database": ["gridgain"],
    "VoltDB|database": ["voltdb", "volt\s+(db|database)"],
    "MemSQL|database": ["memsql"],
    "Android Studio|tool": ["android\s+(studio|sdk)"],
    "Ansible|tool": ["ansible"],
    "Ant|tool": ["ant"],
    "Apache Kafka|tool": ["kafka"],
    "Rational ClearCase|tool": ["clearcase"],
    "Confluence|tool": ["confluence"],
    "Crystal Reports|tool": ["crystal\s+reports"],
    "Customer Relationship Management (CRM)|tool": ["crm", "customer\s+relationship\s+management"],
    "Docker|tool": ["docker"],
    "E-Commerce|tool": ["e\s+commerce", "ecommerce", "e-commerce"],
    "Eclipse IDE|tool": ["eclipse"],
    "Enterprise Resource Planning (ERP)|tool": ["erp", "enterprise\s+resource\s+planning"],
    "Firmware|tool": ["firmware"],
    "Git Version Control|tool": ["git"],
    "Hadoop|tool": ["hadoop"],
    "Internet Information Services (IIS)|tool": ["iis", "internet\s+information\s+services"],
    "IntelliJ IDEA|tool": ["intellij"],
    "iPhone OS (iOS)|tool": ["iphone\s+os", "ios"],
    "JBoss|tool": ["jboss"],
    "Jenkins|tool": ["jenkins"],
    "Jira|tool": ["jira"],
    "Kubernetes|tool": ["kubernetes"],
    "Linux|tool": ["(linux|ubuntu|debian|red\s+hat|centos|fedora|suse|gentoo|slackware|arch\s+linux)"],
    "Maven|tool": ["maven"],
    "Microsoft Azure|tool": ["azure"],
    "Microsoft Excel|tool": ["excel"],
    "Microsoft Office|tool": ["msoffice", "(ms|microsoft)\s+office"],
    "Microsoft PowerPoint|tool": ["powerpoint", "power\s+point"],
    "Microsoft Word|tool": ["(ms|microsoft)\s+word"],
    "Microsoft Project|tool": ["(ms|microsoft)\s+project", "msproject"],
    "Perforce|tool": ["perforce"],
    "Salesforce|tool": ["salesforce", "sales\s+force", "salesforce\.com"],
    "Microsoft SharePoint|tool": ["sharepoint", "share\s+point"],
    "Solaris|tool": ["solaris"],
    "SolidWorks|tool": ["solidworks"],
    "Tableau|tool": ["tableau"],
    "Team Foundation Server (TFS)|tool": ["tfs", "team\s+foundation\s+server"],
    "Terraform|tool": ["terraform"],
    "Apache Tomcat|tool": ["tomcat"],
    "Tortoise SVN|tool": ["tortoisesvn", "tortoise"],
    "Unix|tool": ["unix"],
    "Microsoft Visio|tool": ["visio", "msvisio"],
    "Microsoft Visual Studio|tool": ["visual\s+studio"],
    "VMware|tool": ["vmware"],
    "WebLogic|tool": ["weblogic"],
    "Microsoft Windows|tool": ["(ms|microsoft)\s+windows", "windows\s+\d+"],
    "Microsoft Windows Server|tool": ["windows\s+server"],
    "Xcode|tool": ["xcode", "x\s+code"],
    "VSCode|tool": ["vscode", "vs\s+code"],
    "Agile Methodology|software engineering": ["agile"],
    "Algorithms Programming|software engineering": ["algorithm", "algorithms"],
    "Customer Service|general": ["customer\s+service"],
    "Strategic Partnerships|general": ["strategic\s+(partnerships|partnership)"],
    "Amazon Web Services (AWS)|tool": ["aws", "amazon\s+web\s+services"],
    "Android Development|software engineering": ["android\s+development"],
    "API Development|software engineering": ["api\s+development"],
    "Software Development|software engineering": ["(software|application|product)\s+development"],
    "Software Architecture|software engineering": ["(software|application|system|solution)\s+architecture", "(architecture|architectural)\s+design"],
    "Artificial Intelligence (AI)|software engineering": ["artificial\s+intelligence", "ai"],
    "Critical Thinking|general": ["critical\s+thinking"],
    "BackEnd Development|software engineering": ["back\s+end", "backend", "back-end"],
    "Big Data|software engineering": ["big\s+data", "bigdata", "big-data"],
    "Business Analysis|software engineering": ["business\s+analysis"],
    "Business Intelligence (BI)|software engineering": ["business\s+intelligence", "bi"],
    "Cloud Computing|software engineering": ["cloud\s+computing"],
    "Continuous Integration and Continuous Delivery (CI/CD)|software engineering": ["continuous\s+integration", "continuous\s+delivery", "ci/cd", "ci cd"],
    "Data Mining|software engineering": ["data\s+mining"],
    "Data Modeling|software engineering": ["data\s+modeling"],
    "Data Science|software engineering": ["data\s+science"],
    "Data Structures|software engineering": ["data\s+structures"],
    "Data Visualization|software engineering": ["data\s+visualization"],
    "Database Administration|software engineering": ["(database|db)\s+administration"],
    "Database Design|software engineering": ["(database|db)\s+design"],
    "Database Modeling|software engineering": ["(database|db)\s+modeling"],
    "Debugging|software engineering": ["debugging"],
    "Deep Learning|software engineering": ["deep\s+learning"],
    "Design Patterns|software engineering": ["design\s+(pattern|patterns)"],
    "DevOps|software engineering": ["devops"],
    "Disaster Recovery|software engineering": ["disaster\s+recovery"],
    "Distributed Systems|software engineering": ["distributed\s+(systems|system)"],
    "Engineering/Development Management|software engineering": ["(engineering|development)\s+management"],
    "Enterprise Architecture|software engineering": ["enterprise\s+architecture"],
    "Extract Transform Load (ETL)|software engineering": ["extract\s+transform\s+load", "etl"],
    "FrontEnd Development|software engineering": ["front\s+end", "frontend", "front-end"],
    "FullStack Development|software engineering": ["full\s+stack", "fullstack", "full-stack"],
    "Game Design|software engineering": ["game\s+design"],
    "Game Development|software engineering": ["game\s+development"],
    "Google Cloud Platform (GCP)|tool": ["gcp", "google\s+cloud\s+platform"],
    "Information Security|software engineering": ["information\s+security"],
    "iOS Development|software engineering": ["ios\s+development"],
    "IT Management|software engineering": ["it\s+(service)?\s+management", "information\s+technology\s+management"],
    "Information Technology Infrastructure Library (ITIL)|software engineering": ["itil", "information\s+technology\s+infrastructure\s+library"],
    "Machine Learning|software engineering": ["machine\s+learning"],
    "Microservices|software engineering": ["(microservices|microservice)"],
    "Mobile Development|software engineering": ["mobile\s+development", "mobile\s+(app|application|applications)\s+development"],
    "Multithreading|software engineering": ["multithreading", "multi-threading", "multi\s+threading"],
    "Network Administration|software engineering": ["network\s+administration"],
    "NoSQL Databases|database": ["nosql"],
    "Object-Oriented Programming (OOP)|programming language": ["object\s+oriented\s+programming", "oop"],
    "Project Management Professional (PMP)|software engineering": ["pmp", "project\s+management\s+professional"],
    "MacOS|tool": ["macos", "mac\s+os", "os\s+x"],
    "Product Management|software engineering": ["product\s+management"],
    "Project Management|software engineering": ["project\s+management"],
    "Project Planning|software engineering": ["project\s+planning"],
    "Relational Databases|database": ["relational\s+(databases|database)"],
    "REST API WebServices|software engineering": ["restful", "representational/s+state/s+transfer"],
    "Requirements Analysis|software engineering": ["(requirements|requirement)/s+(analysis|gathering)", "business/s+(requirements|requirement)"],
    "Robotics|general": ["(robotics, robotic)"],
    "Software as a Service (SASS)|software engineering": ["sass", "software/s+as/s+a/s+service"],
    "Scalability|software engineering": ["scalability"],
    "Scrum|software engineering": ["scrum"],
    "Software Development Lifecycle (SDLC)|software engineering": ["(sdlc|alm)", "(software|application)/s+(development)?/s+(lifecycle|life)/s+(cycle)?"],
    "Search Engine Optimization (SEO)|software engineering": ["seo", "search/s+engine/s+optimization"],
    "Service Oriented Architecture (SOA)|software engineering": ["soa", "service/s+oriented/s+architecture"],
    "Simple Object Access Protocol (SOAP)|software engineering": ["soap", "service/s+object/s+access/s+protocol"],
    "Software Design|software engineering": ["software/s+design"],
    "Application Security|software engineering": ["application/s+(security|vulnerabilities|vulnerability)"],
    "Software Documentation|software engineering": ["(software|technical)/s+documentation"],
    "Software Engineering|software engineering": ["(software|systems|system)/s+engineering"],
    "Software Project Management|software engineering": ["software/s+project/s+management"],
    "Software Quality Assurance|software engineering": ["software/s+quality/s+assurance"],
    "Software Testing|software engineering": ["(software|regression|blackbox|functional|unit|manual|api)/s+(testing|test|tests)", "(testing|test|tests)/s+(cases|automation|planning)", "user/s+acceptance/s+(testing|test|tests)", "black/s+box/s+(testing|test|tests)"],
    "Team Management|general": ["team/s+management"],
    "Technical Leadership|software engineering": ["technical/s+leadership"],
    "Technical Support|software engineering": ["technical/s+support"],
    "Technical Writing|software engineering": ["technical/s+writting"],
    "Web Development|software engineering": ["web/s+(application)?/s+(development|design)"],
    "Web Services|software engineering": ["web/s+services"],
    "User Experience (UI) and User Interface (UX) Design|software engineering": ["user/s+(experience|interface)", "(ui|ux)/s+design", "(ui|ux)/s+(//)?(ui|ux)"],
    "Unified Modeling Language (UML)|software engineering": ["uml", "unified/s+modeling/s+language"],
    "eXtensible Stylesheet Language for Transformation (XSLT)|software engineering": ["xslt"],
    "Lamport TeX (LaTeX)|tool": ["latex"],
    "Automation|software engineering": ["automation"],
    "Computer Hardware|software engineering": ["hardware"],
    "Cyber Security|software engineering": ["cyber/s+security", "cybersecurity"],
    "Data Analysis|software engineering": ["data/s+analysis"],
    "Entrepreneurship|general": ["entrepreneurship"],
    "Google Analytics|software engineering": ["google/s+analytics"],
    "Graphic Design|software engineering": ["graphic/s+design"],
    "Leadership|general": ["leadership"],
    "Mentoring and Training|general": ["(mentoring|teaching|training|coaching)"],
    "Problem Solving|general": ["problem/s+solving"],
    "Process Improvement|general": ["process/s+improvement"],
    "Public Speaking|general": ["public/s+speaking"],
    "Quality Assurance|general": ["quality/s+assurance"],
    "Research|general": ["research"],
    "Statistics|general": ["statistics"],
    "System Administration|software engineering": ["(system|systems)/s+administration"],
    "Systems Analysis|software engineering": ["(system|systems)/s+analysis", "analysis/s+services"],
    "Team Building|general": ["team/s+building"],
    "Team Player|general": ["team/s+(//,-)?/s+(player|work)", "(teamwork|teamplayer|collaborative)"],
    "Telecommunications|software engineering": ["(telecommunications|telecommunication)"],
    "Time Management|general": ["time/s+management"],
    ".NET Framework|framework": ["(dotnet|net|/.net)/s+framework", "dot/s+net/s+framework"],
    "JavaScript Object Notation (JSON)|software engineering" : ["json", "javascript/s+object/s+notation"],
    "Troubleshooting|general": ["troubleshooting"],
    "Strategic Planning|general": ["strategic/s+planning"],
    "Enterprise Software|software engineering": ["enterprise/s+software"],
    "Communication|general": ["communication"],
    "Apache Subversion (SVN)|software engineering": ["svn", "apache/s+subversion"],
    "GitHub|tool": ["github"],
    "GitLab|tool": ["gitlab"],
    "Embedded Systems|software engineering": ["embedded/s+(systems|system|software)"],
    "Application Programming Interfaces (API)|software engineering": ["(api|apis)", "application/s+programming/s+(interfaces|interface)"],
    "Recruiting|general": ["recruiting"],
    "Shell Scripting|software engineering": ["shell/s+(scripting|script)"],
    "Cross-functional Team Leadership|general": ["cross/s+(-)?functional/s+team/s+leadership"],
    "Business Development|general": ["business/s+development"],
    "Computer Science Fundamentals|software engineering": ["computer/s+science"],
    "Test Driven Development (TDD)|software engineering": ["test/s+driven/s+development", "tdd"],
    "Marketing|general": ["marketing"],
    "Data Warehousing|general": ["data/s+warehousing"],
    "Vendor Management|general": ["vendor/s+management"],
    "Consulting|general": ["consulting"],
    "Business Strategy|general": ["business/s+strategy"],
    "Microsoft Active Directory|tool": ["active/s+directory"],
    "Transmission Control Protocol/Internet Protocol (TCP/IP)|software engineering": ["tcp(//|-)?ip", "transmission/s+control/s+protocol", "internet/s+protocol"],
    "Startup Environment Enthusiast|general": ["(startup|startups|start-up|start-ups)"],
    "Analytical Skills|general": ["analytical/s+(skills, skill)"],
    "Information Technology Strategy|software engineering": ["information/s+technology/s+strategy", "it/s+strategy"],
    "Change Management|software engineering": ["change/s+management"],
    "Virtualization|software engineering": ["virtualization"],
    "Account Management|general": ["account/s+management"],
    "AutoCAD|tool": ["autocad"],
    "English|human language": ["english"],
    "Network Security|software engineering": ["network/s+security"],
    "Marketing Strategy|general": ["marketing/s+strategy"],
    "Manufacturing Processes|general": ["manufacturing/s+processes"],
    "Adobe Photoshop|tool": ["adobe/s+photoshop"],
    "Operations Management|general": ["operations/s+management"],
    ".NET Core|framework": ["(dotnet|net|/.net)/s+core", "dot/s+net/s+core"],
    "Sales Management|general": ["sales/s+management"],
    "Data Center Operations|software engineering": ["data/s+center/s+operations"],
    "Event Planning|general": ["event/s+planning"],
    "Social Media Marketing|general": ["social/s+media/s+marketing"],
    "Adobe Creative Suite|tool": ["adobe/s+creative/s+suite"],
    "Data Analytics|software engineering": ["data/s+analytics"],
    "Risk Management|general": ["risk/s+management"],
    "Simulations|general": ["simulations"],
    "Contract Negotiation|general": ["contract/s+negotiation"],
    "Device Drivers Engineering|software engineering": ["device/s+(drivers|driver)"],
    "Computer Vision|software engineering": ["computer/s+vision"],
    "Amazon Elastic Compute Cloud (Amazon EC2)|software engineering": ["elastic/s+compute/s+cloud", "ec2"],
    "AWS Lambda|software engineering": ["(aws|amazon)/s+lambda"],
    "AWS Batch|software engineering": ["(aws|amazon)/s+batch"],
    "Amazon Lightsail|software engineering": ["amazon/s+lightsail"],
    "AWS Elastic Beanstalk|software engineering": ["(aws|amazon)/s+elastic/s+beanstalk"],
    "AWS Fargate|software engineering": ["(aws|amazon)/s+fargate"],
    "AWS Outposts|software engineering": ["(aws|amazon)/s+outposts"],
    "AWS Serverless Application Repository|software engineering": ["(aws|amazon)/s+serverless/s+application/s+repository"],
    "AWS Snow Family|software engineering": ["(aws|amazon)/s+snow/s+family"],
    "Amazon Simple Storage Service (Amazon S3)|software engineering": ["(aws|amazon)/s+s3", "simple/s+storage/s+service"],
    "Amazon Elastic Block Store (Amazon EBS)|software engineering": ["(aws|amazon)/s+ebs", "elastic/s+block/s+store"],
    "Amazon Elastic File System (Amazon EFS)|software engineering": ["(aws|amazon)/s+efs", "elastic/s+file/s+system"],
    "Amazon File Systems (Amazon FSx)|software engineering": ["(aws|amazon)/s+fsx", "(aws|amazon)/s+file/s+systems"],
    "Amazon S3 Glacier|software engineering": ["(aws|amazon)/s+glacier", "s3/s+glacier"],
    "AWS Storage Gateway|software engineering": ["(aws|amazon)/s+storage/s+gateway"],
    "AWS Backup|software engineering": ["(aws|amazon)/s+backup"],
    "Amazon Relational Database Service (Amazon RDS)|software engineering": ["(aws|amazon)/s+rds", "(aws|amazon)/s+relational/s+database/s+service"],
    "Amazon DynamoDB|software engineering": ["dynamodb", "dynamo/s+(db|database)"],
    "Amazon ElastiCache|software engineering": ["(aws|amazon)/s+elasticache"],
    "Amazon Neptune|software engineering": ["(aws|amazon)/s+neptune"],
    "Amazon Redshift|software engineering": ["(aws|amazon)/s+redshift"],
    "AWS Database Migration Service (Amazon DMS)|software engineering": ["(aws|amazon)/s+dms", "(aws|amazon)/s+database/s+migration/s+service"],
    "AWS DocumentDB|software engineering": ["documentdb", "document/s+db"],
    "AWS Timestream|software engineering": ["(aws|amazon)/s+timestream"],
    "Amazon Virtual Private Cloud (Amazon VPC)|software engineering": ["(aws|amazon)/s+vpc", "virtual/s+private/s+cloud"],
    "Amazon Route 53|software engineering": ["route/s+53"],
    "Amazon API Gateway|software engineering": ["(aws|amazon)/s+api/s+gateway"],
    "AWS Direct Connect|software engineering": ["(aws|amazon)/s+direct/s+connect"],
    "AWS App Mesh|software engineering": ["(aws|amazon)/s+app/s+mesh"],
    "Amazon CloudFront|software engineering": ["cloudfront"],
    "AWS Global Accelerator|software engineering": ["(aws|amazon)/s+global/s+accelerator"],
    "AWS Transit Gateway|software engineering": ["(aws|amazon)/s+transit/s+gateway"],
    "AWS PrivateLink|software engineering": ["(aws|amazon)/s+privatelink"],
    "Amazon Elastic Load Balancing (Amazon ELB)|software engineering": ["(aws|amazon)/s+elb", "elastic/s+load/s+balancing"],
    "AWS Identity and Access Management (AWS IAM)|software engineering": ["(aws|amazon)/s+iam", "(aws|amazon)/s+identity/s+and/s+access/s+management"],
    "AWS Organizations|software engineering": ["(aws|amazon)/s+organizations"],
    "AWS Certificate Manager (ACM)|software engineering": ["(aws|amazon)/s+acm", "(aws|amazon)/s+certificate/s+manager"],
    "AWS Secrets Manager|software engineering": ["(aws|amazon)/s+secrets/s+manager"],
    "Amazon Web Application Firewall (AWS WAF)|software engineering": ["(aws|amazon)/s+waf", "(aws|amazon)/s+web/s+application/s+firewall"],
    "Amazon GuardDuty|software engineering": ["(aws|amazon)/s+guardduty"],
    "Amazon Macie|software engineering": ["(aws|amazon)/s+macie"],
    "AWS Shield|software engineering": ["(aws|amazon)/s+shield"],
    "AWS Artifact|software engineering": ["(aws|amazon)/s+artifact"],
    "AWS Single Sign-On (Amazon SSO)|software engineering": ["(aws|amazon)/s+sso", "(aws|amazon)/s+single/s+sign/s+(-)?on"],
    "Amazon Athena|software engineering": ["(aws|amazon)/s+athena"],
    "Amazon Elastic MapReduce (Amazon EMR)|software engineering": ["(aws|amazon)/s+emr", "(aws|amazon)/s+elastic/s+mapreduce", "(aws|amazon)/s+elastic/s+map/s+reduce"],
    "Amazon QuickSight|software engineering": ["quicksight", "quick/s+sight"],
    "Amazon Kinesis|software engineering": ["kinesis"],
    "AWS Data Pipeline|software engineering": ["(aws|amazon)/s+data/s+pipeline"],
    "AWS Glue|software engineering": ["(aws|amazon)/s+glue"],
    "AWS Lake Formation|software engineering": ["(aws|amazon)/s+lake/s+formation"],
    "Amazon Managed Streaming for Apache Kafka (Amazon MSK)|software engineering": ["(aws|amazon)/s+msk", "(aws|amazon)/s+managed/s+streaming/s+for/s+apache/s+kafka"],
    "Amazon SageMaker|software engineering": ["(aws|amazon)/s+sagemaker", "(aws|amazon)/s+sage/s+maker"],
    "Amazon Comprehend|software engineering": ["(aws|amazon)/s+comprehend"],
    "Amazon Lex|software engineering": ["(aws|amazon)/s+lex"],
    "Amazon Polly|software engineering": ["(aws|amazon)/s+polly"],
    "Amazon Rekognition|software engineering": ["(aws|amazon)/s+rekognition"],
    "Amazon TextTract|software engineering": ["(aws|amazon)/s+texttract"],
    "Amazon Translate|software engineering": ["(aws|amazon)/s+translate"],
    "Amazon Transcribe|software engineering": ["(aws|amazon)/s+transcribe"],
    "AWS DeepRacer|software engineering": ["(aws|amazon)/s+deepracer"],
    "AWS DeepLens|software engineering": ["(aws|amazon)/s+deeplens"],
    "AWS DeepComposer|software engineering": ["(aws|amazon)/s+deepcomposer"],
    "Amazon Simple Queue Service (Amazon SQS)|software engineering": ["(aws|amazon)/s+sqs", "(aws|amazon)/s+simple/s+queue/s+service"],
    "Amazon Simple Notification Service (Amazon SNS)|software engineering": ["(aws|amazon)/s+sns", "(aws|amazon)/s+simple/s+notification/s+service"],
    "Amazon EventBridge|software engineering": ["(aws|amazon)/s+eventbridge"],
    "Amazon AppFlow|software engineering": ["(aws|amazon)/s+appflow"],
    "AWS Step Functions|software engineering": ["(aws|amazon)/s+step/s+functions"],
    "AWS Simple Workflow Service (Amazon SWF)|software engineering": ["(aws|amazon)/s+swf", "(aws|amazon)/s+simple/s+workflow/s+service"],
    "Amazon CloudWatch|software engineering": ["cloudwatch"],
    "AWS Auto Scaling|software engineering": ["(aws|amazon)/s+auto/s+scaling"],
    "AWS CloudFormation|software engineering": ["(aws|amazon)/s+cloudformation"],
    "AWS CloudTrail|software engineering": ["(aws|amazon)/s+cloudtrail"],
    "AWS Config|software engineering": ["(aws|amazon)/s+config"],
    "AWS OpsWorks|software engineering": ["(aws|amazon)/s+opsworks"],
    "AWS Service Catalog|software engineering": ["(aws|amazon)/s+service/s+catalog"],
    "AWS Trusted Advisor|software engineering": ["(aws|amazon)/s+trusted/s+advisor"],
    "AWS Well-Architected Tool|software engineering": ["(aws|amazon)/s+well/s+architected/s+tool"],
    "AWS Control Tower|software engineering": ["(aws|amazon)/s+control/s+tower"],
    "AWS IoT Core|software engineering": ["(aws|amazon)/s+iot/s+core"],
    "AWS IoT Device Management|software engineering": ["(aws|amazon)/s+iot/s+device/s+management"],
    "AWS IoT Analytics|software engineering": ["(aws|amazon)/s+iot/s+analytics"],
    "AWS IoT Greengrass|software engineering": ["(aws|amazon)/s+iot/s+greengrass"],
    "Waterfall Methodologies|software engineering": ["waterfall"],
    "Product Marketing|general": ["product/s+marketing"],
    "Customer Satisfaction|general": ["customer/s+satisfaction"],
    "Continuous Improvement|general": ["continuous/s+improvement"],
    "Electrical Engineering|general": ["electrical/s+engineering"],
    "Pre-sales Operations|general": ["pre(-)?sales/s+operations"],
    "Cloud Security|software engineering": ["cloud/s+security"],
    "Data Security|software engineering": ["data/s+security"],
    "Identity and Access Management (IAM)|software engineering": ["identity/s+and/s+access/s+management", "iam"],
    "Incident Response|software engineering": ["incident/s+response"],
    "Security Architecture|software engineering": ["security/s+architecture"],
    "Vulnerability Management|software engineering": ["vulnerability/s+management"],
    "Penetration Testing|software engineering": ["penetration/s+testing"],
    "Security Awareness and Training|software engineering": ["security/s+(awareness|training|advocate)"],
    "Cryptography|software engineering": ["cryptography"],
    "Security Operations|software engineering": ["security/s+operations"],
    "Security Governance and Compliance|software engineering": ["security/s+(governance|compliance)"],
    "Mobile Security|software engineering": ["mobile/s+security"],
    "Wireless Security|software engineering": ["wireless/s+security"],
    "Social Engineering|software engineering": ["social/s+engineering"],
    "Cisco Technologies|software engineering": ["cisco/s+(technologies|technology|systems|system|networks|products)"],
    "Microsoft Exchange|software engineering": ["(ms|microsoft)/s+exchange"],
    "Adobe Illustrator|software engineering": ["adobe/s+illustrator"],
    "Digital Marketing|general": ["digital/s+marketing"],
    "Mathematics|general": ["mathematics"],
    "Image Processing|software engineering": ["image/s+processing"],
    "XHTML|programming language": ["xhtml"],
    "Financial Analysis|general": ["financial/s+analysis"],
    "Six Sigma|general": ["(six|6)/s+sigma", "(six|6)(-)?sigma"],
    "Arduino|software engineering": ["arduino"],
    "Firebase|software engineering": ["firebase"],
    "Software Installation|software engineering": ["software/s+installation"],
    "Security Clearance|general": ["security/s+clearance"],
    "Forecasting|general": ["forecasting"],
    "Labview|tool": ["labview"],
    "Laravel|framework": ["laravel"],
    "Voice over Internet Protocol (VoIP)|software engineering": ["voice/s+over/s+internet/s+protocol", "voip"],
    "Microsoft Power BI|tool": ["power/s+bi", "power(-)?bi"],
    "IBM WebSphere Application Server|tool": ["websphere"],
    "Sales Operations|general": ["sales/s+operations"],
    "Data Migration|software engineering": ["data/s+migration"],
    "Solution Selling|general": ["solution/s+selling"],
    "Microsoft Silverlight|tool": ["silverlight"],
    "Performance Tuning|software engineering": ["performance/s+tuning"],
    "Microcontrollers|software engineering": ["(microcontrollers|microcontroller)"],
    "Management Consulting|general": ["management/s+consulting"],
    "Competitive Analysis|general": ["competitive/s+analysis"],
    "Market Research|general": ["market/s+research"],
    "ActionScript|programming language": ["actionscript", "action(-)?script", "action/s+script"],
    "Groovy|programming language": ["groovy"],
    "Windows Forms|framework": ["windows/s+forms", "windowsforms"],
    "Event Management|general": ["event/s+management"],
    "Healthcare|general": ["healthcare"],
    "Microsoft Visual Basic Scripting Edition (VBScript)|programming language": ["vbscript", "vb(-)?script", "vb/s+script", "visual/s+basic/s+(scripting|script)"],
    "Budget Planning|general": ["budget/s+planning"],
    "Lean Manufacturing|general": ["lean/s+manufacturing"],
    "NumPy|framework": ["numpy"],
    "Real-Time Operating System (RTOS)|software engineering": ["real(-)?time/s+operating/s+system", "real/s+time/s+operating/s+system", "rtos"],
    "Bitbucket|tool": ["bitbucket"],
    "Assembly Language|programming language": ["assembly"],
    "Content Management Systems (CMS)|software engineering": ["content/s+management/s+systems", "cms"],
    "COBOL|programming language": ["cobol"],
    "IT Infrastructure|software engineering": ["it/s+infrastructure"],
    "Java Persistence API (JPA)|framework": ["java/s+persistence/s+api", "jpa"],
    "Business Planning|general": ["business/s+planning"],
    "Retail|general": ["retail"],
    "Qt (toolkit)|framework": ["Qt"],
    "Drupal|framework": ["drupal"],
    "Finance Fundamentals|general": ["finance"],
    "Open-source software (OSS)|software engineering": ["open(-)?source/s+software", "open/s+source/s+software", "oss", "opensource"],
    "ASP Classic|programming language": ["asp\s\w+"],
    "Visual Basic for Application (VBA)|programming language": ["vba", "visual/s+basic/s+for/s+application"],
    "Photography|general": ["photography"],
    "Kanban|general": ["kanban"],
    "Scripting Language|programming language": ["scripting/s+language"],
    "RabbitMQ|tool": ["rabbitmq", "rabbit(-)?mq", "rabbit/s+mq"],
    "Jakarta Enterprise Bean (EJB)|framework": ["jakarta/s+enterprise/s+bean", "ejb"],
    "Domain Name System (DNS)|software engineering": ["domain/s+name/s+system", "dns"],
    "Accounting|general": ["accounting"],
    "VHSIC Hardware Description Language (VHDL)|programming language": ["vhdl", "vhsic/s+hardware/s+description/s+language"],
    "Mechanical Engineering|general": ["mechanical/s+engineering"],
    "Webpack|tool": ["webpack"],
    "Verilog|programming language": ["verilog"],
    "Leadership Development|general": ["leadership/s+development"],
    "IT Operations|software engineering": ["it/s+operations"],
    "Hive|tool": ["hive"],
    "Online Marketing|general": ["online/s+marketing"],
    "Email Marketing|general": ["email/s+marketing"],
    "Supply Chain Management|general": ["supply/s+chain/s+management"],
    "Organization Skills|general": ["organization/s+skills"],
    "Configuration Management|software engineering": ["configuration/s+management"],
    "Public Relations|general": ["public/s+relations"],
    "Linux, Apache, MySQL, and PHP (LAMP)|software engineering": ["lamp"],
    "Creative Problem Solving|general": ["creative/s+problem/s+solving"],
    "NGINX|tool": ["nginx"],
    "Adobe Flash|programming language": ["adobe/s+flash"],
    "Interpersonal Skills|general": ["interpersonal/s+skills"],
    "Cucumber|tool": ["cucumber"],
    "Pandas|framework": ["pandas"],
    "Gradle|tool": ["gradle"],
    "Java Message Service (JMS)|framework": ["java/s+message/s+service", "jms"],
    "System Deployment|software engineering": ["system/s+deployment"],
    "Microsoft Outlook|tool": ["(ms|microsoft)/s+outlook"],
    "System Design|software engineering": ["system/s+design"],
    "System Applications and Products (SAP)|tool": ["sap"],
    "Cloud Applications|software engineering": ["cloud/s+applications"],
    "Heroku|tool": ["heroku"],
    "Backbone.JS|framework": ["(backbone./js|backbonejs)", "backbone/s+js", "backbone(-)?js"],
    "Product Design|general": ["product/s+design"],
    "Direct Sales|general": ["direct/s+sales"],
    "Natural Language Processing (NLP)|software engineering": ["natural/s+language/s+processing", "nlp"],
    "Human Resources (HR)|general": ["human/s+resources", "hr"],
    "Project Portfolio Management|general": ["project/s+portfolio/s+management"],
    "OpenCV|framework": ["opencv"],
    "Sales Process|general": ["sales/s+process"],
    "Information Assurance|software engineering": ["information/s+assurance"],
    "Splunk Technology|tool": ["splunk"],
    "Spanish|human language": ["spanish"],
    "NetBeans|tool": ["netbeans"],
    "Aerospace|general": ["aerospace"],
    "Jest|framework": ["jest"],
    "Microsoft Visual C++|programming language": ["visual/s+c++"],
    "Postman API|tool": ["postman"],
    "Data Engineering|software engineering": ["data/s+engineering"],
    "Virtual Private Network (VPN)|software engineering": ["virtual/s+private/s+network", "vpn"],
    "SoapUI|tool": ["soapui"],
    "go-to-market (GTM) strategy|general": ["go(-)?to(-)?market/s+strategy", "go/s+to/s+market/s+strategy", "gtm"],
    "Test Management|software engineering": ["test/s+management"],
    "Contract Management|general": ["contract/s+management"],
    "Presentation Skills|general": ["presentation/s+skills"],
    "Blockchain Technology|software engineering": ["blockchain"],
    "Concurrent Versioning System (CVS)|software engineering": ["concurrent/s+versioning/s+system", "cvs"],
    "Adobe InDesign|tool": ["indesign"],
    "Online Advertising|general": ["online/s+advertising"],
    "Scikit-Learn|framework": ["scikit"],
    "Functional Programming|software engineering": ["functional/s+programming"],
    "Requirements Management|software engineering": ["requirements/s+management"],
    "B2B (business-to-business)|general": ["b2b", "business(-)?to(-)?business", "business/s+to/s+business"],
    "MapReduce|framework": ["mapreduce"],
    "Data Integration|software engineering": ["data/s+integration"],
    "Proposal Writing|general": ["proposal/s+writing"],
    "Big Data Analytics|software engineering": ["big/s+data/s+analytics"],
    "Data Entry|software engineering": ["data/s+entry"],
    "Executive Management|general": ["executive/s+management"],
    "Quality Center|tool": ["quality/s+center"],
    "Adobe Dreamweaver|tool": ["dreamweaver"],
    "JavaServer Faces (JSF)|framework": ["javaserver/s+faces", "jsf"],
    "Signal Processing|software engineering": ["signal/s+processing"],
    "Performance Testing|software engineering": ["performance/s+testing"],
    "Embedded C|programming language": ["embedded/s+c"],
    "Project Engineering|general": ["project/s+engineering"],
    "Marketing Communications|general": ["marketing/s+communications"],
    "People Management|general": ["people/s+management"],
    "Network Design|software engineering": ["network/s+design"],
    "Help Desk Support|software engineering": ["help/s+desk/s+support"],
    "Game Programming|software engineering": ["game/s+programming"],
    "Data Management|software engineering": ["data/s+management"],
    "High Availability|software engineering": ["high/s+availability"],
    "Web Analytics|software engineering": ["web/s+analytics"],
    "Computer-Aided Design (CAD)|tool": ["computer(-)?aided/s+design", "computer/s+aided/s+design", "cad"],
    "Database Development|software engineering": ["database/s+development"],
    "PyTorch|framework": ["pytorch"],
    "Customer Support|general": ["customer/s+support"],
    "Project Management Office (PMO)|general": ["project/s+management/s+office", "pmo"],
    "Network Architecture|software engineering": ["network/s+architecture"],
    "Physics|general": ["physics"],
    "Wireless Networking|software engineering": ["wireless/s+networking"],
    "ArcGIS|tool": ["arcgis"],
    "Information Architecture|software engineering": ["information/s+architecture"],
    "Software Implementation|software engineering": ["software/s+implementation"],
}